server:
  port: 8080


spring:
  redis:
    host: 218.108.153.254
    port: 6379
    password: zhaoyuxing
  servlet:
    multipart:
      max-file-size: 600MB
      enabled: true
      max-request-size: 1000MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://218.108.153.254:3306/sxr_dev?prepStmtCacheSize=517&cachePrepStmts=true&autoReconnect=true&characterEncoding=utf-8&allowMultiQueries=true
    username: www
    password: www
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update





#log
logging:
  config: classpath:logback-boot.xml


#com.mugu.filePath: D:\\my\\
#com.mugu.snpMapfile: scz2.fullsnp
#com.mugu.m6aMap: m6ASNPmap.txt
#com.mugu.outFileName: result.txt
#com.mugu.gtexPath: D:\\download\\test\\GTEx_Analysis_v7_eQTL\\
#com.mugu.upload: D:\\my\\upload\\

com.mugu.filePath: /home/zhaoyx/javaproject/gene/
com.mugu.snpMapfile: scz2.fullsnp
com.mugu.m6aMap: m6ASNPmap.txt
com.mugu.outFileName: result.txt
com.mugu.gtexPath: /home/zhaoyx/javaproject/gene/GTEx_Analysis_v7_eQTL/
com.mugu.upload: /home/zhaoyx/javaproject/gene/upload
